<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);IDE0290</NoWarn>
    <NoWarn>$(NoWarn);MSTEST0049</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inkboard.Application\Inkboard.Application.csproj" />
    <ProjectReference Include="..\Inkboard.Domain\Inkboard.Domain.csproj" />
    <ProjectReference Include="..\Inkboard.Infra\Inkboard.Infra.csproj" />
    <ProjectReference Include="..\Inkboard.API\Inkboard.API.csproj" />
  </ItemGroup>

</Project>
